# length function....> len()
name = "Hay you love coding"
print(len(name))
# Alphanumeric function......> variable_name.isalnum()
print(name.isalnum())
print(name.isalpha())
print(name.lower())
print(name.upper())
print(name.count("H"))
print(name.capitalize())
print(name.find("o"))
print(name.replace("o","u"))
print(name.center(21, "*"))
print(name.endswith("coding"))