# length function....> len()
name = "Hay you love coding"
print(len(name))
# Alphanumeric method......> str_name.isalnum()
print(name.isalnum())
# checks Alphabetic method ....>str_name.isalpha()
print(name.isalpha())
# lower method.....>str_name.lower()
print(name.lower())
# upper method .....>str_name.upper()
print(name.upper())
# count method.....>str_name.count("passing argument")
print(name.count("H"))
# capitalize method.........>str_name.capitalize()
print(name.capitalize())
# find method .........>str_name.find("sub_string",start,end)
print(name.find(""))
# replace_method .....>str_name.replace("new","old",count)
print(name.replace("o", "u"))
# center_method.....>str_name.center(width," fill-char")
print(name.center(21, "*"))
# endswith_method.....>str_name.endswith("argument")
print(name.endswith("coding"))
